export const ERR_UNSUPPORTED_LINK = 'ERR_UNSUPPORTED_LINK';
export const ERR_NOT_FOUND_LINK = 'ERR_NOT_FOUND_LINK';
export const ERR_NOT_FOUND_LINK_OR_PRIVATE_ACCOUNT =
  'ERR_NOT_FOUND_LINK_OR_PRIVATE_ACCOUNT';
export const ERR_NOT_SECURED_RESOURCES = 'ERR_NOT_SECURED_RESOURCES';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
