export const ERR_USER_NOT_ACTIVATED = 'ERR_USER_NOT_ACTIVATED';
export const ERR_EMAIL_NOT_FOUND = 'ERR_EMAIL_NOT_FOUND';
export const ERR_EMAIL_ALREADY_EXIST = 'ERR_EMAIL_ALREADY_EXIST';
export const ERR_NOT_FOUND_USER = 'ERR_NOT_FOUND_USER';
export const ERR_GENERATE_TOKEN = 'ERR_GENERATE_TOKEN';
export const ERR_EXPIRED_CODE = 'ERR_EXPIRED_CODE';
export const ERR_NOT_FOUND = 'ERR_NOT_FOUND';
export const ERR_SEND_MAIL = 'ERR_SEND_MAIL';

export const ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN';
export const ERR_UPLOAD_FAILED = 'ERR_UPLOAD_FAILED';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const ERR_GENERATE_FIREBASE_DYNAMIC_LINK =
  'ERR_GENERATE_FIREBASE_DYNAMIC_LINK';
export const ERR_INCORRECT_CODE = 'ERR_INCORRECT_CODE';
